schools = ["Abraham Lincoln Senior High", 
"Academia Moderna", 
"Academies Of Education And Empowerment At Carson H", 
"Academy For Enriched Sciences", 
"Academy For Multilingual Arts And Science At Mervy", 
"Academy Of Medical Arts At Carson High", 
"Academy Of Science And Engineering", 
"Accelerated Charter Elementary", 
"Aggeler Community Day", 
"Alain Leroy Locke College Preparatory Academy", 
"Albert Einstein Continuation", 
"Albion Street Elementary", 
"Aldama Elementary", 
"Alexander Fleming Middle", 
"Alexander Hamilton Senior High", 
"Alexandria Avenue Elementary", 
"Alfonso B. Perez Special Education Center", 
"Alfred B. Nobel Charter Middle", 
"Allesandro Elementary", 
"Alliance 6-12 College-Ready Academy #21", 
"Alliance Alice M. Baxter College-Ready High", 
"Alliance Cindy And Bill Simon Technology Academy H", 
"Alliance College-Ready Academy High 16", 
"Alliance College-Ready Middle Academy 12", 
"Alliance College-Ready Middle Academy 4", 
"Alliance College-Ready Middle Academy 5", 
"Alliance College-Ready Middle Academy 8", 
"Alliance Collins Family College-Ready High", 
"Alliance Dr. Olga Mohan High", 
"Alliance Gertz-Ressler Richard Merkin 6-12 Complex", 
"Alliance Health Services Academy High", 
"Alliance Jack H. Skirball Middle", 
"Alliance Judy Ivie Burton Technology Academy High", 
"Alliance Kory Hunter Middle", 
"Alliance Leadership Middle Academy", 
"Alliance Leichtman-Levine Family Foundation Enviro", 
"Alliance Marc & Eva Stern Math And Science", 
"Alliance Margaret M. Bloomfield Technology Academy", 
"Alliance Morgan Mckinzie High", 
"Alliance Ouchi-O'donovan 6-12 Complex", 
"Alliance Patti And Peter Neuwirth Leadership Acade", 
"Alliance Renee And Meyer Luskin Academy High", 
"Alliance Susan And Eric Smidt Technology High", 
"Alliance Tennenbaum Family Technology High", 
"Alta California Elementary", 
"Alta Loma Elementary", 
"Amanecer Primary Center", 
"Ambler Avenue Elementary", 
"Amelia Earhart Continuation", 
"Amestoy Elementary", 
"Anatola Avenue Elementary", 
"Andasol Avenue Elementary", 
"Andres And Maria Cardenas Elementary", 
"Andrew Carnegie Middle", 
"Angel's Gate (Continuation)", 
"Angeles Mesa Elementary", 
"Animo College Preparatory Academy", 
"Animo Ellen Ochoa Charter Middle", 
"Animo Jackie Robinson High", 
"Animo James B. Taylor Charter Middle", 
"Animo Jefferson Charter Middle", 
"Animo Mae Jemison Charter Middle", 
"Animo Pat Brown", 
"Animo Phillis Wheatley Charter Middle", 
"Animo Ralph Bunche Charter High", 
"Animo South Los Angeles Charter", 
"Animo Venice Charter High", 
"Animo Watts College Preparatory Academy", 
"Animo Western Charter Middle", 
"Animo Westside Charter Middle", 
"Ann Street Elementary", 
"Annalee Avenue Elementary", 
"Annandale Elementary", 
"Apex Academy", 
"Apperson Street Elementary", 
"Apple Academy Charter Public", 
"Aragon Avenue Elementary", 
"Ararat Charter", 
"Arleta High", 
"Arlington Heights Elementary", 
"Arminta Street Elementary", 
"Arroyo Seco Museum Science", 
"Arts In Action Community Charter", 
"Ascot Avenue Elementary", 
"Aspire Centennial College Preparatory Academy", 
"Aspire Firestone Academy Charter", 
"Aspire Gateway Academy Charter", 
"Aspire Inskeep Academy Charter", 
"Aspire Juanita Tate Academy Charter", 
"Aspire Junior Collegiate Academy", 
"Aspire Pacific Academy", 
"Aspire Slauson Academy Charter", 
"Aspire Titan Academy", 
"Atwater Avenue Elementary", 
"Audubon Middle", 
"Augustus F. Hawkins High A Critical Design And Gam", 
"Augustus F. Hawkins High B Community Health Advoca", 
"Augustus F. Hawkins High C Responsible Indigenous", 
"Aurora Elementary", 
"Avalon Gardens Elementary", 
"Avalon High", 
"Balboa Gifted/High Ability Magnet Elementary", 
"Baldwin Hills Elementary", 
"Bandini Street Elementary", 
"Banning Academies Of Creative And Innovative Scien", 
"Barack Obama Global Preparation Academy", 
"Barton Hill Elementary", 
"Bassett Street Elementary", 
"Beachy Avenue Elementary", 
"Beckford Charter For Enriched Studies", 
"Beethoven Street Elementary", 
"Bell Senior High", 
"Bellingham Elementary", 
"Belmont Senior High", 
"Belmont Sh-La Teacher Preparatory Academy", 
"Belvedere Elementary", 
"Belvedere Middle", 
"Benjamin Banneker Special Education Center", 
"Benjamin Franklin Senior High", 
"Berendo Middle", 
"Berenece Carlson Home Hospital", 
"Bert Corona Charter", 
"Bertrand Avenue Elementary", 
"Betty Plasencia Elementary", 
"Birdielee V. Bright Elementary", 
"Birmingham Community Charter High", 
"Blythe Street Elementary", 
"Bonita Street Elementary", 
"Boyle Heights Continuation", 
"Boyle Heights Stem High", 
"Braddock Drive Elementary", 
"Brainard Elementary", 
"Breed Street Elementary", 
"Brentwood Science", 
"Bret Harte Preparatory Middle", 
"Bridge Street Elementary", 
"Bright Star Secondary Charter Academy", 
"Broad Avenue Elementary", 
"Broadacres Avenue Elementary", 
"Broadway Elementary", 
"Brockton Avenue Elementary", 
"Brooklyn Avenue Elementary", 
"Bryson Avenue Elementary", 
"Buchanan Street Elementary", 
"Budlong Avenue Elementary", 
"Burbank Boulevard Elementary", 
"Burton Street Elementary", 
"Bushnell Way Elementary", 
"C. Morley Sellery Special Education Center", 
"Cabrillo Avenue Elementary", 
"Cahuenga Elementary", 
"Cal Burke High", 
"Calabash Charter Academy", 
"Calahan Community Charter", 
"Calvert Charter For Enriched Studies", 
"Camellia Avenue Elementary", 
"Camino Nuevo Academy #2", 
"Camino Nuevo Charter Academy", 
"Camino Nuevo Charter Academy No. 4", 
"Camino Nuevo Charter High", 
"Camino Nuevo Elementary No. 3", 
"Camino Nuevo High No. 2", 
"Canfield Avenue Elementary", 
"Canoga Park Elementary", 
"Canoga Park Senior High", 
"Cantara Street Elementary", 
"Canterbury Avenue Elementary", 
"Canyon Charter Elementary", 
"Capistrano Avenue Elementary", 
"Carlos Santana Arts Academy", 
"Caroldale Learning Community", 
"Carpenter Community Charter", 
"Carson Senior High", 
"Carson Street Elementary", 
"Carson-Gore Academy Of Enviornmental Studies", 
"Carthay Elementary Of Environmental Studies Magnet", 
"Castelar Street Elementary", 
"Castle Heights Elementary", 
"Castlebay Lane Charter", 
"Catskill Avenue Elementary", 
"Cds Elementary", 
"Cds Secondary", 
"Celerity Cardinal Charter", 
"Celerity Dyad Charter", 
"Celerity Nascent Charter", 
"Celerity Octavia Charter", 
"Celerity Palmati Charter", 
"Celerity Troika Charter", 
"Center For Advanced Learning", 
"Central City Value", 
"Central High", 
"Century Park Elementary", 
"Cesar Chavez Elementary", 
"Cesar E. Chavez Learning Academies-Academy Of Scie", 
"Cesar E. Chavez Learning Academies-Social Justice", 
"Cesar E. Chavez Learning Academies-Teacher Prepara", 
"Cesar E. Chavez Learning Academy - Arts/Theatre/En", 
"Champs - Charter Hs Of Arts-Multimedia & Performin", 
"Chandler Learning Academy", 
"Chapman Elementary", 
"Charles Drew Middle", 
"Charles H. Kim Elementary", 
"Charles Leroy Lowman Special Education Center", 
"Charles Maclay Middle", 
"Charles W. Barrett Elementary", 
"Charles White Elementary", 
"Charnock Road Elementary", 
"Chase Street Elementary", 
"Chatsworth Charter High", 
"Chatsworth Park Elementary", 
"Cheremoya Avenue Elementary", 
"Chester W. Nimitz Middle", 
"Cheviot Hills Continuation", 
"Chime Institute's Schwarzenegger Community", 
"Christopher Columbus Middle", 
"Christopher Dena Elementary", 
"Cienega Elementary", 
"Cimarron Avenue Elementary", 
"Citizens Of The World 2", 
"Citizens Of The World 3", 
"Citizens Of The World Charter Hollywood", 
"City Charter Middle", 
"City High", 
"City Language Immersion Charter", 
"City Of Angels", 
"City Terrace Elementary", 
"Clemente Charter", 
"Clifford Street Elementary", 
"Clover Avenue Elementary", 
"Coeur D'alene Avenue Elementary", 
"Cohasset Street Elementary", 
"Coldwater Canyon Elementary", 
"Colfax Charter Elementary", 
"Coliseum Street Elementary", 
"Collegiate Charter High School Of Los Angeles", 
"Columbus Avenue", 
"Commonwealth Avenue Elementary", 
"Communication And Technology At Diego Rivera Learn", 
"Community Magnet Charter Elementary", 
"Community Preparatory Academy", 
"Compton Avenue Elementary", 
"Contreras Learning Center-Academic Leadership Comm", 
"Contreras Learning Center-Los Angeles School Of Gl", 
"Contreras Learning Center-School Of Social Justice", 
"Corona Avenue Elementary", 
"Cowan Avenue Elementary", 
"Crenshaw Arts-Technology Charter High", 
"Crenshaw Science", 
" Technology", 
" Engineering", 
" Math An", 
"Crescent Heights Boulevard Elementary", 
"Crestwood Street Elementary", 
"Crown Preparatory Academy", 
"Dahlia Heights Elementary", 
"Daniel Pearl Journalism & Communications Magnet", 
"Daniel Webster Middle", 
"Danny J. Bakewell", 
" Sr.", 
" Primary Center", 
"Danube Avenue Elementary", 
"Darby Avenue Charter", 
"David Starr Jordan Senior High", 
"David Wark Griffith Middle", 
"Dayton Heights Elementary", 
"Dearborn Elementary Charter Academy", 
"Del Amo Elementary", 
"Delevan Drive Elementary", 
"Denker Avenue Elementary", 
"Diane S. Leichman Special Education Center", 
"Discovery Charter Preparatory #2", 
"Dixie Canyon Community Charter", 
"Dolores Huerta Elementary", 
"Dolores Street Elementary", 
"Dominguez Elementary", 
"Dorothy V. Johnson Community Day", 
"Dorris Place Elementary", 
"Downtown Business High", 
"Downtown Value", 
"Dr. James Edward Jones Primary Center", 
"Dr. Julian Nava Learning Academies-School Of Arts", 
"Dr. Julian Nava Learning Academies-School Of Busin", 
"Dr. Lawrence H. Moore Math", 
" Science", 
" Technology Ac", 
"Dr. Maya Angelou Community High", 
"Dr. Owen Lloyd Knox Elementary", 
"Dr. Sammy Lee Medical And Health Science Magnet El", 
"Dr. Theo. T. Alexander Jr.", 
" Science Center", 
"Dyer Street Elementary", 
"Eagle Rock Elementary", 
"Eagle Rock High", 
"Eagle Tree Continuation", 
"Early College Academy-La Trade Tech College", 
"East Los Angeles Renaissance Academy At Esteban E.", 
"East Valley Senior High", 
"Eastman Avenue Elementary", 
"Edward R. Roybal Learning Center", 
"Edwin Markham Middle", 
"El Camino Real Charter High", 
"El Dorado Avenue Elementary", 
"El Oro Way Charter For Enriched Studies", 
"El Sereno Elementary", 
"El Sereno Middle", 
"Elizabeth Learning Center", 
"Ellen Ochoa Learning Center", 
"Ellington (Duke) High (Continuation)", 
"Elysian Heights Elementary", 
"Emelita Academy Charter", 
"Emerson Community Charter", 
"Enadia Technology Enriched Charter", 
"Encino Charter Elementary", 
"Endeavor College Preparatory Charter", 
"Engineering And Technology Academy At Esteban E. T", 
"Environmental And Social Policy Magnet", 
"Equitas Academy #2", 
"Equitas Academy #3 Charter", 
"Equitas Academy Charter", 
"Ernest Lawrence Middle", 
"Ernest P. Willenberg Special Education Center", 
"Erwin Elementary", 
"Eshelman Avenue Elementary", 
"Esperanza Elementary", 
"Esteban Torres East La Performing Arts Magnet", 
"Estrella Elementary", 
"Euclid Avenue Elementary", 
"Everest Value", 
"Evergreen Avenue Elementary", 
"Evergreen Continuation", 
"Executive Preparatory Academy Of Finance", 
"Extera Public", 
"Extera Public School No. 2", 
"Fair Avenue Elementary", 
"Fairburn Avenue Elementary", 
"Fairfax Senior High", 
"Farmdale Elementary", 
"Felicitas And Gonzalo Mendez High", 
"Fenton Academy For Social And Emotional Learning", 
"Fenton Avenue Charter", 
"Fenton Primary Center", 
"Fenton Stem Academy: Elementary Center For Science", 
"Fernangeles Elementary", 
"Fifteenth Street Elementary", 
"Fifty-Fourth Street Elementary", 
"Fifty-Ninth Street Elementary", 
"Fifty-Second Street Elementary", 
"Figueroa Street Elementary", 
"First Street Elementary", 
"Fishburn Avenue Elementary", 
"Fletcher Drive Elementary", 
"Florence Avenue Elementary", 
"Florence Griffith Joyner Elementary", 
"Florence Nightingale Middle", 
"Ford Boulevard Elementary", 
"Forty-Ninth Street Elementary", 
"Forty-Second Street Elementary", 
"Foshay Learning Center", 
"Fourth Street Elementary", 
"Francisco Bravo Medical Magnet High", 
"Francisco Sepulveda Middle", 
"Frank Del Olmo Elementary", 
"Frank Lanterman", 
"Franklin Avenue Elementary", 
"Frida Kahlo High", 
"Fries Avenue Elementary", 
"Fullbright Avenue Elementary", 
"Gabriella Charter", 
"Garden Grove Elementary", 
"Gardena Elementary", 
"Gardena Senior High", 
"Gardner Street Elementary", 
"Garvanza Elementary", 
"Garza (Carmen Lomas) Primary Center", 
"Gaspar De Portola Middle", 
"Gates Street Elementary", 
"Gault Street Elementary", 
"George De La Torre Jr. Elementary", 
"George Ellery Hale Charter Academy", 
"George K. Porter Middle", 
"George S. Patton Continuation", 
"George Washington Carver Middle", 
"George Washington Preparatory High", 
"Gerald A. Lawson Academy Of The Arts", 
" Mathematics", 
"Germain Academy For Academic Achievement", 
"Gifted Academy Of Mathematics And Entrepreneurial", 
"Glassell Park Elementary", 
"Gledhill Street Elementary", 
"Glen Alta Elementary", 
"Glenfeliz Boulevard Elementary", 
"Glenn Hammond Curtiss Middle", 
"Glenwood Elementary", 
"Global Education Academy", 
"Global Education Academy 2", 
"Global Education Academy Middle", 
"Goethe International Charter", 
"Graham Elementary", 
"Granada Community Charter", 
"Granada Hills Charter High", 
"Grand View Boulevard Elementary", 
"Grant Elementary", 
"Grape Street Elementary", 
"Gratts Learning Academy For Young Scholars (Glays)", 
"Green Design At Diego Rivera Learning Complex", 
"Gridley Street Elementary", 
"Griffin Avenue Elementary", 
"Grover Cleveland Charter High", 
"Gulf Avenue Elementary", 
"Haddon Avenue Elementary", 
"Halldale Elementary", 
"Hamlin Charter Academy", 
"Hancock Park Elementary", 
"Harbor City Elementary", 
"Harbor Teacher Preparation Academy", 
"Harding Street Elementary", 
"Harmony Elementary", 
"Harold Mcalister High (Opportunity)", 
"Harris Newmark Continuation", 
"Harrison Street Elementary", 
"Harry Bridges Span", 
"Hart Street Elementary", 
"Harvard Elementary", 
"Haskell Elementary", 
"Hawaiian Avenue Elementary", 
"Haynes Charter For Enriched Studies", 
"Hazeltine Avenue Elementary", 
"Helen Bernstein High", 
"Heliotrope Avenue Elementary", 
"Henry David Thoreau Continuation", 
"Henry T. Gage Middle", 
"Herrick Avenue Elementary", 
"Hesby Oaks Leadership Charter", 
"High Tech La", 
"Highland Park Continuation", 
"Hilda L. Solis Learning Academy School Of Technolo", 
"Hillcrest Drive Elementary", 
"Hillery T. Broadous Elementary", 
"Hillside Elementary", 
"Hobart Boulevard Elementary", 
"Hollenbeck Middle", 
"Hollywood Primary Center", 
"Hollywood Senior High", 
"Holmes Avenue Elementary", 
"Hooper Avenue Elementary", 
"Hooper Avenue Primary Center", 
"Hoover Street Elementary", 
"Hope Street Elementary", 
"Horace Mann Junior High", 
"Hubbard Street Elementary", 
"Hubert Howe Bancroft Middle", 
"Humanitas Academy Of Art And Technology At Esteban", 
"Humanities And Arts (Harts) Academy Of Los Angeles", 
"Humphreys Avenue Elementary", 
"Huntington Drive Elementary", 
"Huntington Park Elementary", 
"Huntington Park Senior High", 
"Icef Innovation Los Angeles Charter", 
"Icef Vista Elementary Academy", 
"Icef Vista Middle Academy", 
"Independence Continuation", 
"Independence Elementary", 
"Ingenium Charter", 
"Ingenium Charter Middle", 
"International Studies Learning Center At Legacy Hi", 
"Ivanhoe Elementary", 
"Ivy Academia", 
"Ivy Bound Academy Math, Science, And Technology Ch", 
"Ivy Bound Academy Of Math, Science, And Technology", 
"Jack London Community Day", 
"Jack London Continuation", 
"Jaime Escalante Elementary", 
"James A. Garfield Senior High", 
"James J. Mcbride Special Education Center", 
"James Jordan Middle", 
"James Madison Middle", 
"James Monroe High", 
"Jane Addams Continuation", 
"Joaquin Miller Career And Transition Center", 
"John A. Sutter Middle", 
"John Adams Middle", 
"John B. Monlux Elementary", 
"John Burroughs Middle", 
"John C. Fremont Senior High", 
"John F. Kennedy High", 
"John H. Francis Polytechnic", 
"John H. Liechty Middle", 
"John Hope Continuation", 
"John Marshall Senior High", 
"John Muir Middle", 
"John R. Wooden High", 
"John W. Mack Elementary", 
"Johnnie Cochran, Jr., Middle", 
"Joseph Le Conte Middle", 
"Joseph Pomeroy Widney High", 
"Judith F. Baca Arts Academy", 
"Julie Korenstein Elementary", 
"Justice Street Academy Charter", 
"Kenter Canyon Elementary Charter", 
"Kentwood Elementary", 
"Kester Avenue Elementary", 
"King/Drew Medical Magnet High", 
"Kingsley Elementary", 
"Kipp Academy Of Innovation", 
"Kipp Academy Of Opportunity", 
"Kipp Comienza Community Prep", 
"Kipp Empower Academy", 
"Kipp Ignite Academy", 
"Kipp Iluminar Academy", 
"Kipp Los Angeles College Preparatory", 
"Kipp Philosophers Academy", 
"Kipp Promesa Prep", 
"Kipp Raices Academy", 
"Kipp Scholar Academy", 
"Kipp Sol Academy", 
"Kipp Vida Preparatory Academy", 
"Kittridge Street Elementary", 
"Knollwood Preparatory Academy", 
"La Salle Avenue Elementary", 
"Lafayette Park Primary Center", 
"Lake Street Primary", 
"Lanai Road Elementary", 
"Langdon Avenue Elementary", 
"Lankershim Elementary", 
"Larchmont Charter", 
"Lashon Academy", 
"Lassen Elementary", 
"Latona Avenue Elementary", 
"Laurel Elementary", 
"Leadership In Entertainment And Media Arts (Lema)", 
"Leapwood Avenue Elementary", 
"Leland Street Elementary", 
"Lemay Street Elementary", 
"Lenicia B. Weemes Elementary", 
"Leo Politi Elementary", 
"Lexington Avenue Primary Center", 
"Libertas College Preparatory Charter", 
"Liberty Boulevard Elementary", 
"Liggett Street Elementary", 
"Lillian Street Elementary", 
"Limerick Avenue Elementary", 
"Linda Esperanza Marquez High A Huntington Park Ins", 
"Linda Esperanza Marquez High B Libra Academy", 
"Linda Esperanza Marquez High C School Of Social Ju", 
"Lockhurst Drive Charter Elementary", 
"Lockwood Avenue Elementary", 
"Logan Street Elementary", 
"Loma Vista Elementary", 
"Lomita Math/Science/Technology Magnet", 
"Loren Miller Elementary", 
"Lorena Street Elementary", 
"Loreto Street Elementary", 
"Lorne Street Elementary", 
"Los Angeles Academy Middle", 
"Los Angeles Academy Of Arts & Enterprise Charter", 
"Los Angeles Center For Enriched Studies", 
"Los Angeles Elementary", 
"Los Angeles Leadership Academy", 
"Los Angeles Leadership Primary Academy", 
"Los Angeles River At Sonia Sotomayor Learning Acad", 
"Los Angeles Senior High", 
"Los Angeles Unified Alternative Education", 
"Los Feliz Charter School For The Arts", 
"Los Feliz Science/Tech/Engineer/Math/Medicine Magn", 
"Lou Dantzler Preparatory Charter Elementary", 
"Lou Dantzler Preparatory Charter Middle", 
"Lovelia P. Flournoy Elementary", 
"Loyola Village Elementary", 
"Lucille Roybal-Allard Elementary", 
"Luther Burbank Middle", 
"Macarthur Park Elementary School For The Visual An", 
"Madison Elementary", 
"Magnolia Avenue Elementary", 
"Magnolia Science Academy", 
"Magnolia Science Academy 2", 
"Magnolia Science Academy 3", 
"Magnolia Science Academy 4", 
"Magnolia Science Academy 5", 
"Magnolia Science Academy 6", 
"Magnolia Science Academy 7", 
"Magnolia Science Academy Bell", 
"Main Street Elementary", 
"Malabar Street Elementary", 
"Manchester Avenue Elementary", 
"Manhattan Place Elementary", 
"Manual Arts Senior High", 
"Maple Primary Center", 
"Mar Vista Elementary", 
"Marguerite Poindexter Lamotte Elementary", 
"Marianna Avenue Elementary", 
"Marina Del Rey Middle", 
"Mariposa-Nabi Primary Center", 
"Mark Twain Middle", 
"Marlton", 
"Marquez Charter", 
"Martha Escutia Primary Center", 
"Martin Luther King Jr. Elementary", 
"Marvin Elementary", 
"Mary Mcleod Bethune Middle", 
"Math And Science College Preparatory", 
"Math", 
" Science", 
" & Technology Magnet Academy At Roos", 
"Maurice Sendak Elementary", 
"Mayall Street Elementary", 
"Mayberry Street Elementary", 
"Maywood Academy High", 
"Maywood Elementary", 
"Mckinley Avenue Elementary", 
"Melrose Avenue Elementary", 
"Melvin Avenue Elementary", 
"Menlo Avenue Elementary", 
"Metro Charter", 
"Metropolitan Continuation", 
"Meyler Street Elementary", 
"Michelle Obama Elementary", 
"Micheltorena Street Elementary", 
"Mid-City's Prescott School Of Enriched Sciences", 
"Middle College High", 
"Middleton Primary Center", 
"Middleton Street Elementary", 
"Miles Avenue Elementary", 
"Miramonte Elementary", 
"Mission Continuation", 
"Moneta Continuation", 
"Monsenor Oscar Romero Charter Middle", 
"Montague Charter Academy", 
"Montara Avenue Elementary", 
"Monte Vista Street Elementary", 
"Monterey Continuation", 
"Morningside Elementary", 
"Morris K. Hamasaki Elementary", 
"Mountain View Elementary", 
"Mt. Gleason Middle", 
"Mt. Lukens Continuation", 
"Mt. Washington Elementary", 
"Multicultural Learning Center", 
"Multnomah Street Elementary", 
"Murchison Street Elementary", 
"N.E.W. Academy Canoga Park", 
"N.E.W. Academy Of Science And Arts", 
"Napa Street Elementary", 
"Nathaniel Narbonne Senior High", 
"Nava College Preparatory Academy", 
"Nestle Avenue Charter", 
"Nevada Avenue Elementary", 
"Nevin Avenue Elementary", 
"New Designs Charter", 
"New Designs Charter School-Watts", 
"New Heights Charter", 
"New Horizons Charter Academy", 
"New Los Angeles Charter", 
"New Millennium Secondary", 
"New Village Girls Academy", 
"Newcastle Elementary", 
"Ninety-Fifth Street Elementary", 
"Ninety-Ninth Street Elementary", 
"Ninety-Second Street Elementary", 
"Ninety-Sixth Street Elementary", 
"Ninety-Third Street Elementary", 
"Ninth Street Elementary", 
"Noble Avenue Elementary", 
"District Non-Public Non-Sectarian Schools", 
"Nora Sterry Elementary", 
"Normandie Avenue Elementary", 
"Normont Elementary", 
"North Hollywood Senior High", 
"North Valley Military Institute College Preparator", 
"Northridge Academy High", 
"Northridge Middle", 
"Norwood Street Elementary", 
"Nueva Vista Elementary", 
"O'melveny Elementary", 
"Ocean Charter", 
"Odyssey Continuation", 
"Olive Vista Middle", 
"Oliver Wendell Holmes Middle", 
"Olympic Primary Center", 
"One Hundred Eighteenth Street", 
"One Hundred Eighty-Sixth Street Elementary", 
"One Hundred Fifty-Sixth Street Elementary", 
"One Hundred Fifty-Third Street", 
"One Hundred Ninth Street Elementary", 
"One Hundred Seventh Street Elementary", 
"One Hundred Sixteenth Street Elementary", 
"One Hundred Thirty-Fifth Street Elementary", 
"One Hundred Twelfth Street Elementary", 
"One Hundred Twenty-Second Street Elementary", 
"Open Charter Magnet", 
"Orchard Academies 2B", 
"Orchard Academies 2C", 
"Orthopaedic Hospital", 
"Orville Wright Engineering And Design Magnet", 
"Oscar De La Hoya Animo Charter High", 
"Osceola Street Elementary", 
"Our Community Charter", 
"Overland Avenue Elementary", 
"Owensmouth Continuation", 
"Oxnard Street Elementary", 
"Pacific Boulevard", 
"Pacoima Charter Elementary", 
"Pacoima Middle", 
"Palisades Charter Elementary", 
"Palisades Charter High", 
"Palms Elementary", 
"Palms Middle", 
"Panorama City Elementary", 
"Panorama High", 
"Para Los Ninos - Evelyn Thurman Gratts Primary", 
"Para Los Ninos Charter", 
"Para Los Ninos Middle", 
"Park Avenue Elementary", 
"Park Western Place Elementary", 
"Parmelee Avenue Elementary", 
"Parthenia Street Elementary", 
"Paseo Del Rey Fundamental", 
"Pathways Community", 
"Patrick Henry Middle", 
"Paul Revere Charter Middle", 
"Performing Arts Community At Diego Rivera Learning", 
"Phineas Banning Senior High", 
"Phoenix Continuation", 
"Pinewood Avenue Elementary", 
"Pio Pico Middle", 
"Plainview Academic Charter Academy", 
"Playa Del Rey Elementary", 
"Playa Vista Elementary", 
"Plummer Elementary", 
"Point Fermin Elementary", 
"Pomelo Community Charter", 
"Port Of Los Angeles High", 
"Porter Ranch Community", 
"Prepa Tec - Los Angeles", 
"President Avenue Elementary", 
"Primary Academy For Success", 
"Public Policy Charter", 
"Public Service Community At Diego Rivera Learning", 
"Puc Cals Middle And Early College High", 
"Puc Community Charter Elementary", 
"Puc Community Charter Middle And Puc Community Cha", 
"Puc Early College Academy For Leaders And Scholars", 
"Puc Excel Charter Academy", 
"Puc Inspire Charter Academy", 
"Puc Lakeview Charter Academy", 
"Puc Lakeview Charter High", 
"Puc Milagro Charter", 
"Puc Nueva Esperanza Charter Academy", 
"Puc Santa Rosa Charter Academy", 
"Puc Triumph Charter Academy And Puc Triumph Charte", 
"Pueblo De Los Angeles Continuation", 
"Puente Charter", 
"Purche Avenue Elementary", 
"Queen Anne Place Elementary", 
"Quincy Jones Elementary", 
"Ramon C. Cortines School Of Visual And Performing", 
"Ramona Elementary", 
"Ramona Opportunity High", 
"Ranchito Avenue Elementary", 
"Rancho Dominguez Preparatory", 
"Raymond Avenue Elementary", 
"Renaissance Arts Academy", 
"Renaissance Arts Academy K-12", 
"Reseda Elementary", 
"Reseda Senior High", 
"Resolute Academy Charter", 
"Rfk Community Schools-Ambassador School-Global Edu", 
"Rfk Community Schools-Ambassador-Global Leadership", 
"Rfk Community Schools-For The Visual Arts And Huma", 
"Rfk Community Schools-Los Angeles High School Of T", 
"Rfk Community Schools-New Open World Academy K-12", 
"Rfk Community Schools-Ucla Community K-12", 
"Ricardo Lizarraga Elementary", 
"Richard A. Alonzo Community Day", 
"Richard E. Byrd Middle", 
"Richard Henry Dana Middle", 
"Richard Riordan Primary Center", 
"Richland Avenue Elementary", 
"Rio Vista Elementary", 
"Rise Ko Hyang Middle", 
"Ritter Elementary", 
"Riverside Drive Charter", 
"Robert A. Millikan Middle School", 
" Performing Arts", 
"Robert E. Peary Middle", 
"Robert F. Kennedy Elementary", 
"Robert Frost Middle", 
"Robert Fulton College Preparatory", 
"Robert H. Lewis Continuation", 
"Robert Hill Lane Elementary", 
"Robert Louis Stevenson Middle", 
"Rockdale Visual & Performing Arts Magnet", 
"Rosa Parks Learning Center", 
"Roscoe Elementary", 
"Roscomare Road Elementary", 
"Rosemont Avenue Elementary", 
"Rosewood Avenue Elementary", 
"Rowan Avenue Elementary", 
"Roy Romer Middle", 
"Rudecinda Sepulveda Dodson Middle", 
"Russell Elementary", 
"Sal Castro Middle", 
"Sally Ride Elementary: A Smart Academy", 
"Samuel Gompers Middle", 
"San Antonio Continuation", 
"San Antonio Elementary", 
"San Fernando Elementary", 
"San Fernando Institute Of Applied Media", 
"San Fernando Middle", 
"San Fernando Senior High", 
"San Gabriel Avenue Elementary", 
"San Jose Street Elementary", 
"San Miguel Elementary", 
"San Pascual Avenue Elementary", 
"San Pedro Senior High", 
"San Pedro Street Elementary", 
"Santa Monica Boulevard Community Charter", 
"Santee Education Complex", 
"Sara Coughlin Elementary", 
"Saticoy Elementary", 
"Saturn Street Elementary", 
"School Of Business And Tourism At Contreras Learni", 
"School Of History And Dramatic Arts At Sonia Sotom", 
"Science", 
" Technology", 
" Engineering", 
" Arts And Mathema", 
"Second Street Elementary", 
"Selma Avenue Elementary", 
"Serrania Avenue Charter For Enriched Studies", 
"Seventh Street Elementary", 
"Seventy-Fifth Street Elementary", 
"Seventy-Fourth Street Elementary", 
"Sharp Avenue Elementary", 
"Shenandoah Street Elementary", 
"Sheridan Street Elementary", 
"Sherman Oaks Center For Enriched Studies", 
"Sherman Oaks Elementary Charter", 
"Shirley Avenue Elementary", 
"Short Avenue Elementary", 
"Sierra Park Elementary", 
"Sierra Vista Elementary", 
"Simon Rodia Continuation", 
"Sixth Avenue Elementary", 
"Sixty-Eighth Street Elementary", 
"Sixty-First Street Elementary", 
"Sixty-Sixth Street Elementary", 
"Social Justice Leadership Academy At Esteban E. To", 
"Solano Avenue Elementary", 
"Sophia T. Salvin Special Education Center", 
"Soto Street Elementary", 
"South East High", 
"South Gate Middle", 
"South Gate Senior High", 
"South Park Elementary", 
"South Shores/Csudh Visual And Performing Arts", 
"Southeast Middle", 
"Stagg Street Elementary", 
"Stanford Avenue Elementary", 
"Stanford Primary Center", 
"Stanley Mosk Elementary", 
"State Street Elementary", 
"Stella Middle Charter Academy", 
"Stem Academy At Bernstein High", 
"Stephen M. White Middle", 
"Stonehurst Avenue Elementary", 
"Stoner Avenue Elementary", 
"Stoney Point Continuation", 
"Strathern Street Elementary", 
"Student Empowerment Academy", 
"Studio", 
"Summit Preparatory Charter", 
"Sun Valley High", 
"Sun Valley Magnet", 
"Sunland Elementary", 
"Sunny Brae Avenue Elementary", 
"Sunrise Elementary", 
"Superior Street Elementary", 
"Susan Miller Dorsey Senior High", 
"Sven Lokrantz Special Education Center", 
"Sylmar Biotech Health Academy", 
"Sylmar Elementary", 
"Sylmar Leadership Academy", 
"Sylmar Senior High", 
"Sylvan Park Elementary", 
"Synergy Charter Academy", 
"Synergy Kinetic Academy", 
"Synergy Quantum Academy", 
"Taft Charter High", 
"Taper Avenue Elementary", 
"Tarzana Elementary", 
"Teach Academy Of Technologies", 
"Teach Tech Charter High", 
"Telfair Avenue Elementary", 
"Tenth Street Elementary", 
"Teresa Hughes Elementary", 
"The Accelerated", 
"The Incubator", 
"Theodore Roosevelt Senior High", 
"Third Street Elementary", 
"Thirty-Second Street Usc Performing Arts", 
"Thomas A. Edison Middle", 
"Thomas Jefferson Senior High", 
"Thomas Riley High", 
"Thomas Starr King Middle School Film And Media Mag", 
"Toland Way Elementary", 
"Toluca Lake Elementary", 
"Tom Bradley Global Awareness Magnet", 
"Topanga Elementary Charter", 
"Topeka Charter School For Advanced Studies", 
"Towne Avenue Elementary", 
"Tri-C Community Day", 
"Trinity Street Elementary", 
"Tulsa Street Elementary", 
"Tweedy Elementary", 
"Twentieth Street Elementary", 
"Twenty-Eighth Street Elementary", 
"Twenty-Fourth Street Elementary", 
"Two Hundred Thirty-Second Place", 
"Ulysses S. Grant Senior High", 
"Union Avenue Elementary", 
"University Preparatory Value High", 
"University Senior High", 
"Usc East College Prep", 
"Usc Hybrid High", 
"Utah Street Elementary", 
"Valerio Street Elementary", 
"Valley Academy Of Arts And Sciences", 
"Valley Alternative Magnet", 
"Valley Charter Elementary", 
"Valley Charter Middle", 
"Valley View Elementary", 
"Valor Academy High", 
"Valor Academy Middle", 
"Van Deene Avenue Elementary", 
"Van Gogh Charter", 
"Van Ness Avenue Elementary", 
"Van Nuys Elementary", 
"Van Nuys Middle", 
"Van Nuys Senior High", 
"Vanalden Avenue Elementary", 
"Vaughn Next Century Learning Center", 
"Vena Avenue Elementary", 
"Venice Senior High", 
"Verdugo Hills Senior High", 
"Vermont Avenue Elementary", 
"Vernon City Elementary", 
"Victoria Avenue Elementary", 
"Victory Boulevard Elementary", 
"View Park Continuation", 
"View Park Preparatory Accelerated Charter", 
"View Park Preparatory Accelerated Charter Middle", 
"View Park Preparatory Accelerated High", 
"Village Charter Academy", 
"Vine Street Elementary", 
"Vinedale Elementary", 
"Vintage Math/Science/Technology Magnet", 
"Virgil Middle", 
"Virginia Road Elementary", 
"Vista Charter Middle", 
"Vista Del Valle Dual Language Academy", 
"Vista Middle", 
"Visual And Performing Arts At Legacy High School C", 
"Wadsworth Avenue Elementary", 
"Walgrove Avenue Elementary", 
"Wallis Annenberg High", 
"Walnut Park Elementary", 
"Walnut Park Middle A School Of Social Justice And", 
"Walnut Park Middle B Science", 
" Technology", 
" Engineer", 
"Walter Reed Middle", 
"Warner Avenue Elementary", 
"Washington Irving Middle School Math", 
" Music And En", 
"Washington Primary Center", 
"Watts Learning Center", 
"Watts Learning Center Charter Middle", 
"Weigand Avenue Elementary", 
"Welby Way Charter Elementary School And Gifted-Hig", 
"Wesm Health/Sports Medicine", 
"West Adams Preparatory High", 
"West Athens Elementary", 
"West Hollywood Elementary", 
"West Hollywood Opportunity", 
"West Vernon Avenue Elementary", 
"Western Avenue Elementary", 
"Westminster Avenue Elementary", 
"Westport Heights Elementary", 
"Westside Global Awareness Magnet", 
"Westside Innovative School House", 
"Westside Innovative School House Charter Middle", 
"Westwood Charter Elementary", 
"White Point Elementary", 
"Whitman Continuation", 
"Whitney Young Continuation", 
"Wilbur Charter For Enriched Academics", 
"Will Rogers Continuation", 
"William J. Johnston Community Day", 
"William Jefferson Clinton Middle", 
"William Mulholland Middle", 
"William R. Anton Elementary", 
"William Tell Aggeler Opportunity High", 
"Willow Elementary", 
"Wilmington Middle", 
"Wilmington Park Elementary", 
"Wilshire Crest Elementary", 
"Wilshire Park Elementary", 
"Wilton Place Elementary", 
"Windsor Hills Math Science", 
"Winnetka Avenue Elementary", 
"Wisdom Elementary", 
"Wonderland Avenue Elementary", 
"Woodcrest Elementary", 
"Woodlake Elementary Community Charter", 
"Woodland Hills Charter Academy", 
"Woodland Hills Elementary Charter For Enriched Stu", 
"Woodlawn Avenue Elementary", 
"Woodrow Wilson Senior High", 
"Yes Academy", 
"Yorkdale Elementary", 
"Young Oak Kim Academy", 
"Youth Opportunities Unlimited", 
"Ypi Valley Public Charter High", 
"Zane Grey Continuation"];

toSearch = [];

for i in range(0,10):
	query = schools[i] + " computer science";
	query = query.replace(" ", "+");
	toSearch.append(query);

print(toSearch);

import webbrowser, sys

webbrowser.open('https://www.google.com/search?q=' + toSearch[i] + '&oq=' + toSearch[i])


# import time, random
# from xgoogle.xgoogle.search import GoogleSearch, SearchError

# f = open('urls.txt','wb')

# for query in range(0,10):
# 	wt = random.uniform(2, 5)
# 	gs = GoogleSearch(schools[query] + " computer science")
# 	gs.results_per_page = 10
# 	gs.page = 1
# 	results = gs.get_results()
# 	time.sleep(wt)
# 	#print ('This is the %dth iteration and waited %f seconds' % (query, wt))
# 	for res in results:
# 		f.write(res.url.encode("utf8"))
# 		f.write("\n")

# print (Done)
# f.close()

